authorName: default
experimentName: train_evaluator
trialConcurrency: 1
maxTrialNum: 999
trainingServicePlatform: local
localConfig:
  useActiveGpu: True
  gpuIndices: 1
searchSpacePath: ./train_evaluator.json
useAnnotation: false
tuner:
  builtinTunerName: GridSearch
  gpuIndices: 1
trial:
  command: PYTHONPATH=./ python train_evaluator.py
  codeDir: .
  gpuNum: 1